/*
 ### jQuery FCKEditor Plugin v1.22 - 2008-07-31 ###
 * http://www.fyneworks.com/ - diego@fyneworks.com
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 ###
 Project: http://jquery.com/plugins/project/FCKEditor/
 Website: http://www.fyneworks.com/jquery/FCKEditor/
*/
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}(';4(H.w)(3($){$.7($,{2:{I:10,m:{p:{}},h:\'/j/\',8:[],q:11,r:J,y:3(i,v){12{5 x=13.14(i);4(v)x.15(v);6 x.16(z)}17(e){6\'\'}},18:3(i,v){4(19 i==\'1a\'){v=i.1b;i=i.s||i.1c};6 $.2.y(i,v)},A:3(){5 e=$.2.8;1d(5 i=0;i<e.9;i++){5 a=e[i].d;5 b=$.2.y(e[i].s);a.K(b).1e(\'d\').1f(b);4(b!=a.K())B(\'1g L 1h 1i M:\'+\'\\n\'+\'1j N A 1k O\')}},P:3(){5 a=$.2.8,b={},c=[];$.C(a,3(){4($(\'#\'+f.s).9>0)b[f.s]=f});$.C(b,3(){c[c.9]=f});$.2.8=c},Q:3(a){5 o=$.7({},$.2.m||{},a||{});$.7(o,{D:(o.D||\'d.2, d.j\'),k:(o.h||o.k||$.2.h)});5 e=$(o.e);4(!e.9>0)e=$(o.D);4(!e.9>0)6;o=$.7({},o,($.1l?e.O():($.R?e.R():J))||{});4(!$.2.S&&!$.2.q){$.2.S=z;$.1m(o.k+\'j.1n\',3(){$.2.q=z})};5 b=3(){4($.2.q){$.2.E(e,o)}U{4($.2.1o<=0){B(\'w.j M L: 1p 1q 1r 1s 1t 1u.\')}U{$.2.I--;H.1v(b,1w)}}};b(e);6 e},V:3(){4($.2.r)6;$.2.r={u:$.F.u||3(){}};$.F.u=3(){$.2.A();6 $.2.r.u.1x(f,1y)}},E:3(e,o){o=$.7({},$.2.m||{},o||{});$.7(o,{W:(o.1z||o.W||\'1A%\'),X:(o.1B||o.X||\'1C\'),k:(o.h||o.k||$.2.h),Y:(o.1D||o.Y||\'1E\'),p:(o.m||o.p||{})});e=$(e);4(e.1F()>0){5 a=$.2.8;e.C(3(i,t){4((t.G||\'\').1G()!=\'d\')6 B([\'1H 1I 1J 1K 1L 1M N 1N $.j.E 3\',\'G:\'+t.G,\'g:\'+t.g,\'l:\'+t.l].1O(\'\\n\'));5 T=$(t);4(!t.g)t.g=\'2\'+($.2.8.9+1);4(!t.l)t.l=t.g;4(t.l&&!t.2){5 n=a.9;a[n]=1P 1Q(t.g);$.7(a[n],o,o.p||{});a[n].1R();a[n].d=T;t.2=a[n]}});$.2.8=a;$.2.P()};6 e},Z:3(o){$.2.V();6 $.2.Q(o)}}});$.7($.F,{2:3(o){$.2.Z($.7(o||{},{e:f}))}})})(w);',62,116,'||fck|function|if|var|return|extend|editors|length||||textarea||this|name|path||fckeditor|BasePath|id|config|||Config|loaded|intercepted|InstanceName||ajaxSubmit||jQuery||content|true|update|alert|each|selector|editor|fn|tagName|window|waitFor|null|val|error|plugin|to|data|clean|create|metadata|loading||else|intercept|Width|Height|ToolbarSet|start||false|try|FCKeditorAPI|GetInstance|SetHTML|GetXHTML|catch|setHTML|typeof|object|html|instance|for|filter|text|Critical|in|FCK|Unable|form|meta|getScript|js|waited|The|FCKEditor|script|did|not|load|setTimeout|1000|apply|arguments|width|100|height|500px|toolbar|Default|size|toLowerCase|An|invalid|parameter|has|been|passed|the|join|new|FCKeditor|ReplaceTextarea'.split('|'),0,{}))